name: CI

on:
  push:
    tags:
      - "v*.*.*"

jobs: 
  build-docker:
    name: Build and push docker image
    runs-on: ubuntu-latest

    steps:
    - name: Show git ref
      run: echo ${{ github.ref }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build docker images
      run: cd user && docker build -t ghcr.io/hgrf/qemu-rpi-user:latest .

    - name: Login to ghcr
      run: echo ${{ github.token }} | docker login ghcr.io -u hgrf --password-stdin

    - name: Push to ghcr
      run: |
        GITHUB_TAG=${GITHUB_REF#refs/tags/}
        echo "Tag: ${GITHUB_TAG}"
        docker tag ghcr.io/hgrf/qemu-rpi-user:latest ghcr.io/hgrf/qemu-rpi-user:${GITHUB_TAG}
        docker push ghcr.io/hgrf/qemu-rpi-user:latest
        docker push ghcr.io/hgrf/qemu-rpi-user:${GITHUB_TAG}
